# cluster_config.yml - cluster configuration
__default__:
    account: watertemp
    partition: gpu
    time: 03:00:00 # time limit for each job
    nodes: 1
    output: snakejob-%j.out
    error: err-%j.err
    gpu: '--gres gpu:1'


max_eval:
    account: watertemp
    partition: cpu
    time: 02:00:00 # time limit for each job
    nodes: 1
    name: "{rule}"
    output: snakejob-%j.out
    error: err-%j.err
    gpu: ''

min_eval:
    account: watertemp
    partition: cpu
    time: 02:00:00 # time limit for each job
    nodes: 1
    name: "{rule}"
    output: snakejob-%j.out
    error: err-%j.err
    gpu: ''

prep:
    account: watertemp
    partition: cpu
    time: 02:00:00 # time limit for each job
    nodes: 1
    name: "{rule}"
    output: snakejob-%j.out
    error: err-%j.err
    gpu: ''