# Input files
obs_flow: "data/in/obs_flow_subset"
obs_temp: "data/in/obs_temp_subset"
sntemp_file: "data/in/uncal_sntemp_input_output_subset"
adjdata: 'data/in/adj_mat/adj_mx_subset.pkl'

out_dir: 'data/out'
expid: '365_test'
code_dir: "gwn"
clean_prepped: False

## Possible Xvars
## seg_ccov (cloud cover), seg_humid (humidity), seg_outlflow (streamflow out), seg_rain (rainfall), seg_shade (shade_fraction),
## seg_tave_air (air temp), seg_tave_gw (gw temp), seg_tave_sroff (surface runoff temp), seg_tave_upstream (upstream temp), seg_tave_water (water temp),
## seg_upstream_inflow, seg_width, seg_inc_gwflow (groundwater flow), seg_potet (potential ET), seg_sroff (surface runoff), seg_ssflow
## (interflow), seginc_sward (solar radiation), seg_length (length of segment), seg_slope, seg_elev, seg

x_vars: ["seg_rain", "seg_tave_air", "seginc_swrad", "seg_shade", "seg_width", "seg_length", "seginc_potet", "seg_slope", "seg_humid", "seg_elev"]
y_vars: ['seg_tave_water']
primary_variable: 'temp'

seq_length: [365]
# out_dim: 60
batch_size: 10
epochs: 5
epochs_pre: 0
kernel_size: 8
layer_size: 4
learning_rate: 0.001
offset: [1]
scale_y: True

train_start_date:
  - '1985-10-01'
  - '2016-10-01'
train_end_date:
  - '2006-09-30'
  - '2020-09-30'
val_start_date: '2006-10-01'
val_end_date: '2011-09-30'
test_start_date:
  - '1980-10-01'
  - '2011-10-01'
  - '2020-10-01'
test_end_date:
  - '1985-09-30'
  - '2016-09-30'
  - '2021-09-30'
