name: gwn_gpu
channels:
    - conda-forge
    - defaults
    - bioconda
    - pytorch
dependencies:
    - python=3
    - pytorch::pytorch==1.7.1
    - matplotlib
    - pandas
    - xarray
    - bioconda::snakemake
    - seaborn
